dream-num/Luckysheet

docs/guide/data.md, docs/guide/sheet.md
upload the sheet.md and review the data.md
=> danny first commit

src/controllers/formulaBar.js, src/controllers/handler.js, src/controllers/keyboard.js
=> fix(bugs): fix issue #27 #29

src/controllers/dataVerificationCtrl.js, src/controllers/formulaBar.js
fix(validation of "0" values): fix
fix(fix focus after formula edit): fix
fix(event name): fix
=> Minor fixes

gulpfile.js, package.json
=> feat: build target es5

src/controllers/freezen.js
去掉freezen 为null 才重新生成freezen的判断，改成每次都重新生成，防止旧数据影响
=> 重新生成freezen

src/controllers/postil.js
Fixed issue https://github.com/mengshukeji/Luckysheet/issues/130
=> make comments work in frozen cells

src/controllers/handler.js, src/controllers/imageCtrl.js, src/controllers/server.js, src/controllers/sheetBar.js, src/index.html
=> fix(fix #212): cancel highlight

package.json, src/controllers/print.js
=> remove: jspdf

docs/zh/guide/api.md
=> 更新create函数文档说明

src/controllers/server.js, src/global/extend.js
Solve the problem  增加行不生效 #294 
The reason for the problem is that the **new Function** accesses **_global variables_** at execution time
=> Solve the problem  增加行不生效 #294 

src/controllers/sheetmanage.js
解决 [BUG]setSheetDelete时有个bug #329
=> showsheetbarConfig.sheet == false 工作表不可见 删除sheet报错问题

src/controllers/constant.js, src/controllers/sheetBar.js, src/css/luckysheet-core.css
Solve the problem of sheetRightClickConfig优化 #339
=> Sheetrightclickconfig optimization

src/config.js, src/controllers/constant.js, src/controllers/luckysheetConfigsetting.js, src/css/luckysheet-core.css, src/index.html
=> fix(fix #290): userinfo

src/global/api.js
解决[BUG] 通过setCellValue函数更新单元格之后cellUpdated钩子函数不会触发 #354
=> APi：setCellValue cellUpdated Hook  execute

src/controllers/handler.js, src/css/luckysheet-core.css, src/expendPlugins/chart/plugin.js, src/index.html
设置图表可拖动区域高亮效果，鼠标经过可拖动区域时鼠标显示十字，不可拖动区域显示箭头
=> 图表拖动时鼠标高亮效果

src/global/api.js
=> 数组排序错误，导致getRangeHtml错位

src/controllers/sheetBar.js, src/locale/zh.js
解决 [Feature request]重命名为空的弹窗提示改为普通提示弹窗 #484
=> 调整重命名sheet提示框

src/global/getRowlen.js
resolve [BUG]发现一个BUG，在行号处右键设置行号，先复制、再粘贴单元格后，行高变成默认值 #672
=> fix 修复bug#672

docs/zh/guide/sheet.md, src/controllers/dataVerificationCtrl.js, src/css/luckysheet-core.css, src/locale/en.js, src/locale/es.js, src/locale/zh.js, src/locale/zh_tw.js
=> feature: 下拉选择列表支持多选 #559

src/controllers/protection.js, src/controllers/select.js
启用loadSheetUrl参数时隐藏显示sheet报错 BUG
=> fix bug #563

src/controllers/select.js
=> fixed bug: #565

docs/guide/config.md, docs/zh/guide/config.md, src/controllers/server.js
* 协作消息钩子#567
* 增加补充文档中文
* 增加补充文档英文
=> Feature: #567 协作消息钩子

src/controllers/handler.js, src/controllers/selection.js
=> fixed: #573 复制多行文本（inlineStr）类型的单元格无法复制和粘贴

src/controllers/rowColumnOperation.js, src/global/api.js
增加右键删除和增加行的钩子函数，rowInsertBefore: function(index,value, direction) 和rowDeleteBefore: function( st, ed)
增加向下插入行insertRowBottom和向右插入列insertColumnRight
=> 增加快捷删除和增加行的钩子函数

src/controllers/updateCell.js, src/global/formula.js
[fix #550](https://github.com/mengshukeji/Luckysheet/issues/550)
=> fix: filter xss

gulpfile.js, package.json, src/controllers/menuButton.js, src/index.js
=> build(esbuild): add esbuild

src/global/extend.js
=> fix：#744 修复从从excel中过来的边框在插入时未正确复制的bug

src/controllers/dataVerificationCtrl.js
=> fix(dataVerificationCtrl.js)： 更新手机号校验规则

src/controllers/dataVerificationCtrl.js
=> fix(dataVerificationCtrl.js): 优化身份证验证规则

src/controllers/dataVerificationCtrl.js
=> fix(dataVerificationCtrl): 修复文本长度验证切换选项时 下面输入框不切换的问题

src/controllers/searchReplace.js
=> fix(search): 查找搜索的错误，未勾选正则时，也是正则搜索

src/controllers/menuButton.js
=> fix: 修复换行单元格在mergecell时内容丢失的bug

docs/zh/guide/config.md, src/controllers/sheetBar.js, src/controllers/sheetmanage.js
实现/新增以下 sheet 相关的钩子函数
- sheetCreateBefore
- sheetCreateAfter
- sheetCopyBefore
- sheetCopyAfter
- sheetHideBefore
- sheetHideAfter
- sheetShowBefore
- sheetShowAfter
- sheetDeleteBefore
- sheetDeleteAfter
- sheetEditNameBefore
- sheetEditNameAfter
=> 实现 sheet 相关的钩子函数

src/controllers/handler.js, src/controllers/listener.js, src/controllers/toolbar.js, src/css/luckysheet-core.css
=> fix: undo rodo 不可用时图标灰化

src/controllers/zoom.js
RT, 参考腾讯文档、语雀中的表格，系统缩放快捷键按下时，会缩放表格而非整个浏览器
=> feat: 监听系统 Ctrl + +/-/0/wheel 的缩放，同步到表格

src/controllers/postil.js, src/global/extend.js
- fix(postil): 修复插入行列的时候批注被复制的问题
- fix(postil):  修复批注鼠标悬浮显示时，大小和编辑状态不一致的问题
- fix(postil): 修复 commentUpdateBefore 钩子中的bug 修复 return false 的情况下，编辑批注无法消失的bug
=> Fix/postil 批注相关bug修复

src/controllers/menuButton.js, src/controllers/protection.js, src/css/luckysheet-core.css
修复问题1：修复了保护工作表的提示语placeHolder为undefined的问题
修复问题2：修复英语语种下，插入链接弹窗的链接地址栏显示错误问题
修复问题3：修复英文下，合并单元格的拓展菜单UI显示问题
**问题1截图：**
**问题1修复：**
**问题2截图：**
**问题2修复：**
**问题3截图**
**问题3修复**
=> fix: 修复UI显示问题

src/controllers/handler.js, src/controllers/keyboard.js, src/controllers/menuButton.js, src/controllers/rowColumnOperation.js, src/global/validate.js
现在设置allowEdit为false，禁止进行前台编辑时，还有很多功能可以进行操作，并且改变表格的结构、数据等。
进行了一波修复。
=> fix: 修复了一波在禁止编辑情况下仍然可以编辑的问题。

src/global/extend.js
问题1：对第表格一列的左侧添加列时，添加出来的列数据会同步
问题2：在合并单元格内右键添加行列会出现渲染问题 #853 
问题3：在只有一行的合并单元格内添加行会变成增高这个合并单元格。
问题4：在只有一列的合并单元格内添加列会变成曾宽这个合并单元格。
**问题1复现场景：**
1. 进入一个sheet
2. 选择第一列的某个单元格右键
3. 点击插入列
4. 随便编辑插入出来的那一列中的某个单元格
**PS：有的时候要新建一个sheet才会复现**
**修改前截图：**
**修改后截图：**
**问题2复现场景：**
1. 先合并一块单元格
2. 鼠标右键在合并单元格内，添加行、添加列。
**修改前截图：**
**修改后截图**
**问题3复现场景**
1.先合并一个行高只有1的合并单元格
2.选中合并单元格右键添加行
**问题期望：**
我在合并单元格的边界向外新增行列，理应是新增正常的行列而不是合并单元格的一部分
**修改前截图**
**修改后截图**
问题4与问题3类似，就没有截图了
=> fix: 解决四个添加行列的问题

src/controllers/hyperlinkCtrl.js
=> fix: 修复协同编辑下的插入超链接问题

src/controllers/menuButton.js
=> fix(freezen): 修复PR#843中修改遗漏处理冻结到选区的问题

src/global/api.js
=> 修复没有配置默认行高列宽时，去取工作表的行高列宽返回undefined

README-zh.md, README.md
添加 Vue3+Vite 使用Luckysheet的示例项目，含有在线演示
=> feat: add Vue3 + Vite demo

src/controllers/handler.js
Hi!
When I paste copied table i get nothing. But expected result is data table.
Example of table:
`<table data-number-column="false">
<tbody>
<tr>
<th rowspan="1" colspan="1" colorname="" class="ak-renderer-tableHeader-sortable-column" data-colwidth="226.67" aria-sort="none">
<div class="ak-renderer-tableHeader-sortable-column__button" role="button" tabindex="0" aria-disabled="false">
<p data-renderer-start-pos="4"><strong data-renderer-mark="true">1</strong></p>
<figure aria-hidden="true" class="ak-renderer-tableHeader-sorting-icon ak-renderer-tableHeader-sorting-icon__no-order">
<div role="presentation">
<figure class=" css-1tsmyfw">
<div class="sorting-icon-svg__no_order table-sorting-icon-inactive css-1trp9h6"></div>
</figure>
</div>
</figure>
</div>
</th>
<th rowspan="1" colspan="1" …
=> fix issue on paste table with th elements in first row

src/controllers/selection.js, src/locale/en.js, src/locale/es.js, src/locale/zh.js, src/locale/zh_tw.js
This PR localizes some hardcoded Chinese texts.
=> Localize hardcoded texts

.gitignore, src/controllers/selection.js, src/controllers/updateCell.js, src/global/formula.js
1: fix edit box and function box shows error data when cell value contains "<" and ">" sign. 
2: fix copy paste data error when cell value contains "<", ">" sign. 
3: add .vscode to gitignore
fix #1060
=> fix: cell data contains "<" sign

src/global/sort.js
Localize some error messages using these existing keys:
https://github.com/mengshukeji/Luckysheet/blob/abbbebe16d778b26ed813a9ab843df2c1d613bd2/src/locale/zh.js#L9519-L9520
=> Localize hardcoded texts (in `sort.js`)

src/controllers/sheetmanage.js
Sheet name length could exceed 31 char
Sheet name could take into account another sheet name that contains but not starts with the name (sheets: ABCD(Copy), BCD; copying BCD results in BCD(Copy2))
=> Fixed issues when copying sheets

src/controllers/menuButton.js
=> fix: #409: `freeze range` fixes the upper left corner of the range

src/controllers/handler.js
=> fix: 修复截图位置偏移

src/controllers/sheetMove.js
Issues No : https://github.com/mengshukeji/Luckysheet/issues/1134
The app stops running when the merged cell is selected by the keyboard.
+1, -1 in the cell area function to fall into an infinite loop.
@mengshukeji
=> Fixed merge cell move

docs/guide/resource.md, docs/zh/guide/resource.md
如题，在社区案例处加了我做的服务端的链接
https://github.com/TitanRGB/Luckysheet-ExpressReact-Example
其实很初级，我本人也没啥前后端开发的经验。不过社区案例那里确实只有 Java Go 和 NET，所以就希望加个 Node-Express 方案的。虽然我这样不用数据库的方案，只够做一些很轻量级的个人应用，但也确实有很窄的应用场景，而且也可以给其他新手借鉴
=> [Edit Webpage Documentation] 网页文档，在社区案例处自荐一下我做的服务端

src/function/functionImplementation.js
=> Fix #1175: INDEX function should behave like Excel's INDEX on horizontal ranges

src/global/formula.js
https://github.com/dream-num/Luckysheet/issues/1246
=> fix incorrect references when referencing worksheet cells link #1246

src/function/functionImplementation.js
=> Fix if formula calculate error

src/global/format.js
修复数字超过16位时候的精度丢失问题，将超过16位的数字使用字符串文本返回。
=> 关于长数字的精度丢失问题

src/global/extend.js
=> fix(issue #1326): right click to delete cell error
