- src/function/functionImplementation.js
如不过滤，计算结果不正确，Excel中会忽略范围中的null值的
1. 选区范围中没有空值，IRR计算结果是77.84%
2. 把C1删除后，IRR计算结果是115.45%
1. 选区范围中没有空值，IRR计算结果77.84%
2. 把C1删除后，IRR计算结果77.83%（**错误结果**）
**源码中functionImplementation.js第15809行，values = values.concat(func_methods.getCellDataArr(data_values, "number", false));
这个方法getCellDataArr的第三个参数是isNeglectNullCell，应该设置为true，可以过滤掉单元格为null的值，与Excel的算法一致**
> IRR公式，需要过滤范围单元格中的null空值

- src/controllers/sheetmanage.js
初始化时，如果多个表单都设置成活跃状态，或者index都设置成一样或者都未设置，就会出现多个表单都是勾选状态或者都未勾选。在表单进行状态切换时，会导致代码报错。
> fix: 初始化表单状态下标调整

- src/controllers/cellDatePickerCtrl.js
> fix: 解决单击非时间日期单元格后还会跳出日期时间弹框

- src/global/api.js
发现了个bug:
当我使用 setCellFormat 设置数据后， 此时撤销一次命令，这个时候再去点击页面单元格，会报错：（luckysheet_select_save.push is not a function），因为此时 Store.luckysheet_select_save 是一个对象；主要是这个函数调用时引起的， 第二参数应该是个数组或 undefined。
tips: 这次更改的有效代码应该就一行，可能把空格给删了，所以显示有多行
> fix: jfrefreshgrid 函数第二个参数应该是个数组

- src/function/func.js
- src/global/formula.js
主要修改了src/global/formula.js的functionParser、isFunctionRange、execFunctionGroup、execfunction、functionHTML、getcellrange函数中与单、双引号处理的代码。
1、现在能处理="3"+3&""""""""这类带“”公式，输出结果为6"""
2、能处理sheet名字包含-()等字符以及包含单引号'【但不能在首尾位置】例如：Sheet2重命名为"1'-2(副本) 公式为='"1''-2(副本)'!A1就能正确引用"1'-2(副本)表A1单元格内容
3、修改了functionHTML让输入='1-2'!A1时候原本2'!A1是红色，'1-是黑色的问题。
4、修复了A1为5，A2公式=A1，A3公式=A1+A2，删除A1的值后，A3变成#VALUE!的错误。
> formula.js公式修改

- src/controllers/sheetBar.js
- src/locale/zh.js
- src/methods/get.js
修改了src/methods/get.js的getRangetxt函数。
解决了在单元格输入=后鼠标选择其他sheet的单元格后，公式栏显示公式不根据情况都不加单引号的bug。例如：sheet2重命名为1-2，在sheet1里A1单元格输入=后，鼠标点1-2的A1单元格后，公式栏显示公式=1-2!A1，这种公式是错误的。正确应该是='1-2'!A1
> 修改了src/methods/get.js的getRangetxt

- src/global/extend.js
说明：表格在操作删除多行后，会把同一个row空数组(引用类型)添加成为data多行的数据源，导致设置这些行数据时产生错误，本次提交解决删除多行操作递补空白行引起的设置cell值错误。
> 解决删除多行操作递补空白行引起的设置cell值错误

- src/controllers/menuButton.js
- src/global/api.js
操作步骤： 
（1）合并单元格
（2）取消合并单元格
（3）在取消合并后的某个单元格内编辑内容
问题描述：
整块区域的N个单元格联动（设置了某个单元格的内容为 “优秀”，则周边合并单元格范围内所有的单元格都被设置为 “优秀”）
> 解决合并单元格后取消合并操作创建cell的地址引用问题

- src/config.js
- src/controllers/imageUpdateCtrl.js
- src/controllers/server.js
- src/core.js
由于当前使用websocket同步消息，所以遇到较大的图片的时候，就会发生wss连接异常导致wss断开的现象，因此我添加了全局自定义图片同步方法的功能，可以自定义图片发给后台的方式，比如ajax方式，该方法已经用到了我自己的项目里面了，我的项目最终使用ajax提交图片到后台，后台wss传到前台。参考：https://github.com/liuqiao1995/luckysheet_django，
该功能提交id： https://github.com/liuqiao1995/Luckysheet/commit/5b00ea2cced8e228f2b7cd02385e9092c3618c9a
为实现该功能最终添加了如下代码：
1. 首先src/config.js里面添加自定义图片的发送配置
2. 把该配置添加到src/core.js里面
3. 添加一个自定义src/controllers/imageUpdateCtrl.js文件，把发送图片函数写进去
4. src/controllers/server.js里面修改原来的wss发送配置
该功能使用方法如下（可自行修改）：
src/config.js里面修改imageUpdateMethodConfig配置：:{"method":"POST", "url":"http://127.0.0.1:8000/luckysheetupdateurl"}
> 添加自定义图片同步方法的功能

- gulpfile.js
- src/controllers/constant.js
- src/css/luckysheet-core.css
> 样式优化，工具栏在拖动高度后单元格下拉仍居中显示

- src/global/draw.js
> fix(draw.js): 数字格式的单元格值为字符串时设置条件格式为数据条会报错

- src/global/cursorPos.js
如其他地方在 document 上直接派发事件，此时event.target为document，无classList，此处代码会报错。
> fix(cursorPos): 修复 event.target 为 document 等情况下代码报错的问题

- src/controllers/pivotTable.js
声明了全局的const = pivotTable；在函数内部，redo["pivotTable"] = pivotTable;  和 let pivotTable = _this.getPivotTableData(); 这两句会导致代码报错
> fix: 修复数据透视 数据声明bug

- docs/zh/guide/config.md
- src/controllers/handler.js
- src/controllers/luckysheetConfigsetting.js
- src/core.js
- src/global/createdom.js
新增 `addRowCount` 配置项
```js
var options = {
container: 'sheet', //luckysheet为容器id
// 自定义默认新增行的数目
addRowCount: 10
};
luckysheet.create(options);
```
可修改如下位置默认新增的行数目
> feat(config) : 默认的新增行数目作为配置项

- src/global/refresh.js
RT, 就改了一行代码，可看下是否有问题。
#823 
之前：
新的效果
> fix: 修复初始config为空的清空下，粘贴后撤销，边距等信息未正确撤销的问题

- src/controllers/server.js
#827 
**问题描述：**
A用户不断添加sheet，直到出现sheet滚动按钮，而B用户不断收到ws转发的添加sheet的OP，但是B用户处理OP添加完sheet后不会出现滚动按钮，即使已经超出了屏幕宽度的70%而被截断了
**问题原因：**
其余用户收到ws广播的添加sheet的OP时，做的处理没有去对是否显示滚动按钮做判断
**解决方案：**
在server.js文件处理新建sheet的OP结束后，调用sheetmanage.locationSheet()，计算是否显示滚动按钮
**之前效果：**
**改之后效果：**
> fix: 修复添加sheet时，接受OP方的sheet滚动按钮显示问题

- docs/zh/guide/config.md
- src/controllers/handler.js
- src/controllers/imageCtrl.js
之前的图片配置为
```js
{
"type": "3",
"src": "非常大的base64，可能几十kb，甚至几MB",
"originWidth": 1224,
"originHeight": 888,
"default": {
"width": 825,
"height": 599,
"left": 98,
"top": 83
},
"crop": {
"width": 825,
"height": 599,
"offsetLeft": 0,
"offsetTop": 0
},
"isFixedPos": false,
"fixedLeft": 46,
"fixedTop": 130,
"border": {
"width": 0,
"radius": 0,
"style": "solid",
"color": "#000"
}
}
```
现在可以是
```js
{
"type": "3",
"src": "rest/attach/[fileguid]",
"originWidth": 1224,
"originHeight": 888,
"default": {
"width": 825,
"height": 599,
"left": 98,
"top": 83
},
"crop": {
"width": 825,
"height": 599,
"offsetLeft": 0,
"offsetTop": 0
},
"isFixedPos": false,
"fixedLeft": 46,
"fixedTop": 130,
"border": {
"width": 0,
"radius": 0,
"style": "solid",
"color": "#000"
}
}
```
> 新增图片单独上传，sheet中引入图片地址的实现，解决图片较大或较多时，数据过大的问题

- src/controllers/sheetmanage.js
#832
**问题描述：**
1. 服务端已有sheet1、sheet2两张表，且都有数据。
2. A、B都是刚进入的状态，只打开了sheet1。
3. A打开sheet2显示正常且有数据。
4. B新增一个sheet后，再打开sheet2，发现没有从服务端拉数据
**问题原因：**
B用户新增sheet，初始化新增的这个sheet的数据之后，会去加载所有未加载的sheet数据。但是调用loadOtherFile方法最后走到了getdata.js里的datagridgrowth方法里面去初始化数据而没有从服务端拉。初始化后的数据就跟服务端存的数据不同了。
**解决方案：**
注释sheetmanage.js里changeSheet方法里的loadOtherFile，不调用即可。没有必要把其余未加载的sheet的数据全都加载出来（更何况loadOtherFile的加载最后是把初始化用的数据写入进去）
**之前效果：**
**改之后效果：**
> fix: 修复添加sheet后的数据丢失问题.

- src/controllers/sheetBar.js
#835 
**问题描述：**
重命名sheet为空时弹出tooltip提示，会导致阻止无法关闭，阻止任意下一步
**问题原因：**
重命名校验这里的交互，当判断输入是空时，会弹出tooltip提示并focus重命名的输入框，这时候点击tooltip的关闭或者任意地方就又会触发blur失焦事件再次tooltip，所以阻止了任意的下一步操作。
**解决方案：**
修改交互为，判断输入的不符合规则，tooltip提示错误类型，并充值sheet名称为原本的值，并关闭输入框。目前业界内的在线表格都是这样做的。
**之前效果：**
**改之后效果：**
> fix: 修复重命名sheet为空时的tooltipbug，修改重命名的交互。

- src/controllers/server.js
- src/controllers/sheetmanage.js
#838 
**问题描述：**
1. 添加sheet直到右下角出现滚动按钮
2. 删除sheet（或者隐藏sheet）
3. 可以发现滚动按钮会一直存在，即使最后删除到只剩一个sheet
PS：协同情况下，上述操作对于其余接收OP的用户也是一样没有判断滚动按钮。
**问题原因：**
删除sheet的逻辑，先要走一次sheet隐藏的setSheetHide方法，而在这个方法中，没有对隐藏sheet之后的sheet栏滚动按钮是否显示做处理。
**解决方案：**
setSheetHide方法处理完后，加入locationSheet方法判断是否显示，并修改locationSheet方法的判断，当sheet栏的占宽不宽于屏幕宽的70%时，隐藏滚动按钮。
**删除sheet截图gif：**
**隐藏sheet截图gif：**
**修改后效果：**
> fix: 修复隐藏和删除sheet时，右下角的滚动按钮不会重新计算的问题

- src/controllers/sheetBar.js
#840 
**问题描述：**
协同编辑，点击重命名，出现input框，输入后还未失焦保存。
右键其余的sheet，触发失焦和sheet的右击事件。
会发现其余接收到OP的用户，重命名的sheet和实际不符
**问题原因：**
重命名sheet时，会去取Store.currentSheetIndex的值作为OP里的值，而我们右键点击了sheet后触发了mousedown事件，会切换当前使用的sheet（改变了Store.currentSheetIndex），而mousedown事件触发的又比blur事件早，所以广播给其他用户的值就会有问题。
**解决方案：**
改变mousedown和blur的触发顺序
**修改前效果**：
**修改后效果：**
> fix: 修复协同编辑情况下的重命名sheet后OP广播错误问题

- src/controllers/server.js
正常来说，协同编辑情况下，光标同步后的用户名，hover上去显示的用户名应该是完整的用户名。
**之前：**
现在：****
> feat: 修改协同编辑的光标提示，hover上去显示完整用户名

- src/controllers/freezen.js
- src/controllers/handler.js
- src/controllers/menuButton.js
- src/global/api.js
- src/locale/en.js
- src/locale/es.js
- src/locale/zh.js
- src/locale/zh_tw.js
#815 
冻结首行实际是冻结了当前视图的第一行
重现步骤：
1. 向下滚动若干行
2. 选择冻结首行
3. 当前屏幕内的第一行位置被冻结，如下图实际为25行
新版效果：
在此过程中发现 office、wps 中的首行首列实际是指当前滚动区域内的第一行第一列，而非实际数据的第一行第一列。
照这个来看，luckysheet的表现是对的，但实际上luckysheet也存在问题。
如果是冻结滚动后视图的第一行第一列，那么仅仅存储 `{type: row }` 来表示首行就是不对的， 比如滚动到10行的位置，冻结，当前显示是冻结到第十行，第十行之前都看不到。 保存数据，再次进来，此时冻结变成了冻结第一行， 因此这是也个bug。
直觉理解上实际的第一更对，但以excel为标杆，则不是这样。
为了这个差异，修复是加了个标志位来判到底使用何种冻结方式。
```js
{
// 定义冻结首行、首列是实际的第一行第一列还是当前视图的第一行第一列
// excel 为视图的第一行第一列，但此处实现有问题，如滚动到15行冻结首行，当前冻结了15行，保存再进去实际冻结了第一行
// 冻结真实的第一行、第一列更符合直觉
freezenRealFirstRowColumn: true
}
```
将此值设置为false就是之前的表现， true就是冻结实际第一行第一列的表现。
> 修复冻结首行实际是冻结了当前视图的第一行的问题

- src/controllers/resize.js
#579 #845 
跟579这个issue是同个问题导致，之前有人修了一版加了个判断，但并没有解决根本问题。
**复现场景：**
1. luckysheet引入在项目中，表格的容器不是全屏（容器左侧有margin值）
2. 容器的ID不设为luckysheet
3. 点击“更多按钮”
4. 能够发现更多按钮的出现错位
**修改前截图：**
**修改后效果图**
> fix: 解决容器id不是luckysheet时，点击工具栏中 “更多” 按钮，出现的偏移位置出错的问题

- src/global/extend.js
**复现场景：**
1. 鼠标右键，添加多列
2. 在添加出来的单元格内输入
3. 查看
**修改前截图：**
**修改后截图：**
> fix: 修复右键添加多列时，添加出来的cell单元格数据会同步的问题

- src/controllers/server.js
**复现步骤：**
1. 用户B进入编辑，用户A出现用户B的光标提示
2. 用户A点击新增列
3. A报错
**修改前gif：**
**修改后gif：**
> fix: 修复协同编辑情况下，他人正在编辑时，修改行高列宽和添加行列报错的问题

- src/global/draw.js
**问题描述：**
现在的背景色填充，会把默认的边框给盖掉，盖住之后就看不见区域内是否有合并单元格等，如果设置的背景色为白色，就会导致视觉效果上会缺失一整块（全白）
**复现步骤：**
用户选中一块区域，设置背景色为黄色
发现选区内的默认边框统统被覆盖
**修改前效果：**
**修改后效果：**
> fix(draw.js): 修复背景色会盖过边框的问题

- src/controllers/menuButton.js
**问题描述：**
如果我通过标题栏选中了部分的合并单元格，点击格式刷可正确点击，但是不能正常的复制样式。
**修改前截图：**
**修改后截图：**
> fix(menuButton.js): 修复选中部分合并单元格时，格式刷渲染错误的问题

- src/controllers/server.js
**问题描述：**
协同编辑情况下，当光标选在了左上靠边的位置时，显示的光标会被遮挡
**问题截图：**
> fix(server.js): 修复协同编辑器i情况下，如果光标在左上的边接处显示不全的问题

- src/controllers/inlineString.js
假设一个单元格的内容是luckysheet,其中ky两个字母是设置了加粗的样式,
那此时如果我选中luckysheet,也就是选中全部,给选中的内容设置一个删除线的样式.
得到的效果会是:
只有luc和sheet才有斜体的效果,而ky并没有被设置成删除线样式.
这和用户预期的效果的不一致. 
具体可以看issue描述
fix # 917
https://github.com/mengshukeji/Luckysheet/issues/917
> fix(src/controllers/inlinestring.js updateinlinestringformat): 内联样式设置的时候，会对部分内容失效

- src/controllers/dropCell.js
In the function called execFunctionGroup, the row and col arguments are mixed up in places
> fix: dropCell.update function

- src/global/getRowlen.js
The computeRowlenByContent function performs calculation for hidden columns too and it's affect on view
> fix: computeRowlenByContent function, skip hidden columns

- src/controllers/inlineString.js
- src/global/formula.js
**1.部分样式回车换行覆盖问题：**
2.当单元格是合并单元格时，不应该自适应行高
> 修复行高自适应场景问题、部分样式时回车换行样式覆盖问题

- src/global/getRowlen.js
文档中描述 cell.mc.cs 为 合并单元格占的列数
原代码使用 mc.c !== mc.cs 意为 开始列不等于合并列数？
在实际使用中遇到了，第3列刚好合并了3列，跳过了这个if，导致列宽计算出来依然是第3列的列宽
应当是合并列数为1的时候 ( 即只合并了行，没有合并列 )跳过
> fixed：某些极限情况下合并单元格的列宽计算错误

- src/core.js
- src/locale/locale.js
This PR exposes the `localeObj` of `locale.js` by including it in the core `luckysheet` object with the name `locales`.
This allows library users to add locales.
```js
luckysheet.locales.ja = { ... };
```
In some cases, it is not practical to translate all the localizable words, but only some of them.
Such cases can also be handled.
```js
luckysheet.locales.ja = {
...luckysheet.locales.en,
toolbar: {
...luckysheet.locales.en.toolbar,
undo: '元に戻す',
},
};
```
> feat: allow library users to add locales

- src/controllers/searchReplace.js
On the latest `master` branch, case-insensitive searches work as case-sensitive searches.
It seems to be a degrade due to the following commit:
https://github.com/mengshukeji/Luckysheet/commit/6970f47f8475d754069040c76219eea69a7f4a70
This PR fixes the case-insensitive search.
> fix: case-insensitive search becomes case-sensitive

- src/controllers/toolbar.js
Excel:
Luckysheet (current):
Currently, increase/decrease decimal places is reversed. This PR fixes it.
> fix: increase/decrease decimal places was reversed

- src/core.js
- src/function/functionlist.js
This is very helpful for scenarios where the custom function is very domain-specific and does not make sense to add to the Luckysheet codebase.
Developer will have to be cognizant of locales and needs to handle providing the appropriate text based on the current locale.
> Allow to dynamically add custom functions at runtime

- src/global/api.js
在实际使用中遇到仅缩放操作按钮能更新图片位置及大小，setSheetZoom API不能
> fix: 修复调用 setSheetZoom API时图片未更新的问题

- src/function/functionImplementation.js
"moment" - don't use what caused the error anymore.
format ('MM-DD') without a year cannot parse the date correctly (returns a string)
> Fix datediff

- src/controllers/controlHistory.js
- src/controllers/rowColumnOperation.js
- src/global/refresh.js
Currently, when a cell is cleared, the hyperlink remains.
There is no way to remove the hyperlink on UI.
This PR fixes that clearing cell removes the hyperlink.
> fix: clearing cell removes hyperlink

- src/controllers/controlHistory.js
- src/controllers/menuButton.js
- src/global/refresh.js
Currently, merging cells clears the values and formulas in the merged cells, but does not update the `calcChain` and `hyperlink`.
This PR fixed it.
> fix: update calcChain and hyperlink on merge cells

- src/global/formula.js
Currently, copying the `B1` cell having the formula `=A1` to the `A2` cell produces the formula `=2`.
This PR fixes it to produces `=#REF!` as in Excel.
> fix: copying B1 having "=A1" to A2 generates "#REF!" instead of "=2"

- src/global/getdata.js
跳过datagridgrowth函数内coladd为空时执行的 [].concat(coladd), 极大提升加载速度
> 跳过coladd长度为0时非常耗时的循环

- src/controllers/filter.js
合并单元格在筛选时只显示了主单元格, 非主单元格归属于空白单元格了
fix #1309
> fix(src/controllers/filter.js): 合并单元格筛选异常

- src/global/api.js
> fix: 修复 setCellValue 方法bug 仅当新设置的单元格不含有公式时才能删除原公式链 fixed#1367 

- src/controllers/sheetBar.js
修复当sheetRightClickConfig的rename为false时，仍然可以通过双击底部sheet名称来进行工作表重命名的问题。
> fix:修复禁用sheet菜单重命名时，仍可双击sheet名称来重命名的问题。

- src/controllers/filter.js
问题复现步骤：
1. 将B列隐藏
2. 将A-C列区域数据作为筛选选取
3. 筛选A列或C列数据
4. 选择按值过滤
此时会发现，筛选值列表与实际列数据不符
（原因是，隐藏列后，未隐藏创建的筛选dom标签，导致标签重叠，获取到的是其他下标列的row数据）
> fix: 解决有隐藏列时筛选数据错乱的问题

- .prettierignore
- .prettierrc.json
- package.json
Hey! 
This pull request allows you to format the codebase and unify it across all developers automatically.
To do that I suppose to use [Prettier](https://prettier.io/). 
Prettier is an opinionated code formatter
I made a simple config that you can [adjust](https://prettier.io/docs/en/options.html) to your needs.
There are two scripts in the `package.json`
1. prettier - check all files
2. prettier:fix - format all files
You need to make a new PR with `prettier:fix` to format the whole old codebase
Also, Prettier can [integrate](https://prettier.io/docs/en/editors.html) with most editors
To see examples check the [playground](https://prettier.io/playground/)
> Prettier support
